### ISSUE TITLE
Code: Lines 26-34

### ISSUE THREAD

**Issue by stanley-godfrey** [aronhnt/Hangman#1]
Isn't that code taken directly from your Error Checking repository on GH? If so, you could have just downloaded that file and imported in in Python like:
``` python3
import error_check

error_check.check(...)  # I don't know that actual module/function name
```

**Comment by aronhnt** [comment]
True, didn't actually think of that!
(Hopefully will fix this later)

**Comment by aronhnt** [comment]
Done this (hopefully). If you find any other problems drop me another issue.
